/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type IPCategory = { 'trademark' : null } |
  { 'copyright' : null } |
  { 'patent' : null };
export interface IPRecord {
  'id' : bigint,
  'documentHash' : Uint8Array,
  'title' : string,
  'owner' : Principal,
  'hash' : string,
  'fileBlob' : [] | [ExternalBlob],
  'description' : string,
  'jurisdiction' : string,
  'category' : IPCategory,
  'registrationDate' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'organisation' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Filter IPs by category.
   */
  'filterByCategory' : ActorMethod<[IPCategory], Array<IPRecord>>,
  /**
   * / Filter IPs by jurisdiction.
   */
  'filterByJurisdiction' : ActorMethod<[string], Array<IPRecord>>,
  /**
   * / Filter IPs by owner principal.
   */
  'filterByOwner' : ActorMethod<[Principal], Array<IPRecord>>,
  /**
   * / List all registered IPs (paginated). Pass offset=0 and limit=50 for the
   * / first page.
   */
  'getAllIPs' : ActorMethod<[bigint, bigint], Array<IPRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Retrieve a single IP record by its unique ID.
   */
  'getIP' : ActorMethod<[bigint], [] | [IPRecord]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerIP' : ActorMethod<
    [
      string,
      string,
      IPCategory,
      Uint8Array,
      [] | [ExternalBlob],
      string,
      string,
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search IPs whose title contains the given keyword (case-sensitive).
   */
  'searchByTitle' : ActorMethod<[string], Array<IPRecord>>,
  /**
   * / Search IPs by title or hash (case-insensitive for titles, case-insensitive for hashes).
   */
  'searchByTitleOrHash' : ActorMethod<[string], Array<IPRecord>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];