/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TokenBalance = IDL.Nat64;
export const IPCategory = IDL.Variant({
  'trademark' : IDL.Null,
  'copyright' : IDL.Null,
  'patent' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const IPRecord = IDL.Record({
  'id' : IDL.Nat,
  'documentHash' : IDL.Vec(IDL.Nat8),
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'fileBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'jurisdiction' : IDL.Text,
  'category' : IPCategory,
  'registrationDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'organisation' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'burnTokens' : IDL.Func([TokenBalance], [], []),
  'filterByCategory' : IDL.Func([IPCategory], [IDL.Vec(IPRecord)], ['query']),
  'filterByJurisdiction' : IDL.Func([IDL.Text], [IDL.Vec(IPRecord)], ['query']),
  'filterByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(IPRecord)], ['query']),
  'getAllIPs' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(IPRecord)], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [TokenBalance], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCirculatingSupply' : IDL.Func([], [IDL.Nat], ['query']),
  'getIP' : IDL.Func([IDL.Nat], [IDL.Opt(IPRecord)], ['query']),
  'getTotalBurnedTokens' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeTreasury' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerIP' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IPCategory,
        IDL.Vec(IDL.Nat8),
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(IPRecord)], ['query']),
  'transferTokens' : IDL.Func([IDL.Principal, TokenBalance], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TokenBalance = IDL.Nat64;
  const IPCategory = IDL.Variant({
    'trademark' : IDL.Null,
    'copyright' : IDL.Null,
    'patent' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const IPRecord = IDL.Record({
    'id' : IDL.Nat,
    'documentHash' : IDL.Vec(IDL.Nat8),
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'fileBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'jurisdiction' : IDL.Text,
    'category' : IPCategory,
    'registrationDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'organisation' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'burnTokens' : IDL.Func([TokenBalance], [], []),
    'filterByCategory' : IDL.Func([IPCategory], [IDL.Vec(IPRecord)], ['query']),
    'filterByJurisdiction' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IPRecord)],
        ['query'],
      ),
    'filterByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(IPRecord)], ['query']),
    'getAllIPs' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(IPRecord)], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [TokenBalance], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCirculatingSupply' : IDL.Func([], [IDL.Nat], ['query']),
    'getIP' : IDL.Func([IDL.Nat], [IDL.Opt(IPRecord)], ['query']),
    'getTotalBurnedTokens' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeTreasury' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerIP' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IPCategory,
          IDL.Vec(IDL.Nat8),
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(IPRecord)], ['query']),
    'transferTokens' : IDL.Func([IDL.Principal, TokenBalance], [], []),
  });
};

export const init = ({ IDL }) => { return []; };